config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users

  get '/lunches/match', to: 'lunches#match' 
  get '/lunches/cancel_next_lunch', to: 'lunches#cancel_next_lunch' 

  resources :lunches
  resources :matches

  get  'static_pages/conversations'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :users
end

app/models/lunch.rb
class Lunch < ApplicationRecord
  has_and_belongs_to_many :users, -> { distinct }
  has_and_belongs_to_many :matches, -> { distinct }

  def self.match
    next_lunch_start = Date.current.next_week(:thursday) + 12.hours
    lunch = self.includes(:users).find_by(start: next_lunch_start)
    users = lunch.users.dup.shuffle

    if users.count >= 2
      lunch.matches.delete_all

      users.each do |u1|
        match = Match.new
        match.lunches << lunch unless match.lunches.include?(lunch)

        users.delete(u1)
        match.users << u1 unless match.users.include?(u1)

        u2 = users.sample
        users.delete(u2)
        match.users << u2 unless match.users.include?(u2)

        # if only one user left
        if users.count == 1
          u3 = users.last
          puts u3
          users.delete(u3)
          match.users << u3 unless match.users.include?(u3)
        end

        puts match
        match.save
      end
    end
  end

  def self.fake
    Lunch.create!
  end

end

app/models/match.rb
class Match < ApplicationRecord
  has_and_belongs_to_many :lunches, -> { distinct }
  has_and_belongs_to_many :users, -> { distinct }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :department

  has_and_belongs_to_many :lunches, -> { distinct }
  has_and_belongs_to_many :matches, -> { distinct }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    lunches_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      puts user_params
      user_params.permit(:email, :password, :password_confirmation, :name, :department_id)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to lunches_url
    else
      render "home/landing_page"
    end
  end
end

app/controllers/lunches_controller.rb
require 'date'

class LunchesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find_by_id(current_user)

    @next_lunch_start = Date.current.next_week(:thursday) + 12.hours

    lunches = Lunch.joins(:users).where("(users.id = ?) AND (lunches.start = ?)", current_user.id, @next_lunch_start)

    if lunches.count == 1
      @lunch = lunches[0]
      #NotifierMailer.joined_lunch(@user).deliver_now
    end

    matches = Match.joins(:users,:lunches).where("(users.id = ?) AND (lunches.start = ?)", current_user.id, @next_lunch_start)

    if matches.count == 1
      @users = User.joins(:matches).where("(matches.id = ?) AND (users.id != ?)", matches[0].id, current_user.id)
    end

    @random_users = User.all.take(5)
  end

  def create
    next_lunch_start = Date.current.next_week(:thursday) + 12.hours
    @lunch = Lunch.includes(:users).find_or_create_by(start: next_lunch_start)
    @lunch.users << current_user unless @lunch.users.include?(current_user)
    @lunch.save

    redirect_to lunches_path
  end

  def cancel_next_lunch
    next_lunch_start = Date.current.next_week(:thursday) + 12.hours
    @lunch = Lunch.includes(:users).find_or_create_by(start: next_lunch_start)
    puts @lunch.users.count
    @lunch.users.delete(current_user)
    puts @lunch.users.count
    @lunch.save

    redirect_to '/lunches/match'
  end

  def match
    Lunch.match
    redirect_to lunches_path
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
    def index 
        @matches = Match.all.reverse
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def conversations

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new 
    @user =  User.new
    @departments = Department.all
  end

  def create
    # @department = Department.find(user_params[:department])
    # user_params[:department] = @department
    puts user_params
    @user = User.new(user_params)

    if @user.save
      NotifierMailer.with(user: @user).welcome.deliver_later
      redirect_to "/"
    else
      puts @user.errors.full_messages
      render 'new'
    end
  end

def show
  @user = User.find(params[:id])
end

def index
  @users = User.all
end



  private
    def user_params
      params.require(:user).permit(:name, :email, :url, :department_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lunches_helper.rb
module LunchesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/global_partials/_header.html.erb
<header>
    <span class="logo"><%= link_to "Qiao", root_url %></span>
</header>

app/views/global_partials/_notice.html.erb
<% if notice %>
<p class="notice"><%= notice %></p>
<% elsif alert %>
<p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qiao</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render "global_partials/header" %>
    <%= render "global_partials/notice" %>
    <div class="content-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lunches/index.html.erb
<% if user_signed_in? %>
    <div class="user-feed-card">
        <div class="card-content">
        <span>
            <img src="<%= image_path('face.png') %>" class="face"/>
        </span>
        <span>
            <h3>Welcome</h3>
            <h2><%= link_to @user.name, @user %></h2>
        </span>
        </div>
    </div>
<% end %>


  <% if @lunch %>
    <div class="section-heading">
        <h1>Upcoming</h1>
        <p>Here's the lunch you've joined</p>
    </div>
    <div class="event">
        <div class="event-content">
            <h3><%= @next_lunch_start.strftime('%B %Y') %></h3>
            <h2><%= @next_lunch_start.strftime('%A %d') %></h2>
            <h2>at 12:00</h2>
              <div class="content">
                <% if @users %>
                  <p>with
                  <% @users.each_with_index do |user, i| %>
                     <span class="name"><%= link_to user.name , user_path(user.id)%></span>
                    <% if i != @users.count - 1 %>
                      and 
                    <% end %>
                  <% end %>
                <% end %>
                </p>
              </div>

            <div class="button black">
                <%= link_to "Cancel", '/lunches/cancel_next_lunch' %>
            </div>
        </div>
    </div>
    <div class="section-heading">
        <h1>Conversations</h1>
        <p>Avoid an akward silence</p>
    </div>

    <div class="event-conversations">
        <div class="event-content">
            <h3>Topic</h3>
            <h2>What is the worst thing you have eaten?</h2>
            <div class="button pink">
                <%= link_to "See All", static_pages_conversations_url %>
            </div>
        </div>
    </div>
  <% else %>
    <div class="section-heading">
        <h1>Join Lunch</h1>
        <p>Sign up to join the next lunch round</p>
    </div>
    <div class="event">
        <div class="event-content">
            <h3><%= Date.current.next_week(:thursday).strftime('%B %Y')  %></h3>
            <h2><%= Date.current.next_week(:thursday).strftime('%A %d %B')  %></h2>
            <h2>at 12:00</h2>
            <div class="button pink">
                <%= link_to "Join", lunches_path, method: :post %>
            </div>
        </div>
    </div>
  <% end %>

<div class="section-heading">
    <h1>Previously</h1>
    <p>See the lunches you have been on before</p>
</div>

<div class="prev-container">
    <div class="lunch">
        <div class="content">
            <h3 class="date">3 may</h3>
            <p>with <span class="name"><%= link_to @random_users[0].name, user_path(@random_users[0].id)%></span> and 
            <span class="name"><%= link_to @random_users[1].name, user_path(@random_users[1].id)%></span></p>
        </div>
    </div>
    <div class="lunch">
        <div class="content">
            <h3 class="date">28 april</h3>
            <p>with <span class="name"><%= link_to @random_users[2].name, user_path(@random_users[2].id)%></span></p>
        </div>
    </div>
       <div class="lunch">
        <div class="content">
            <h3 class="date">9 april</h3>
            <p>with <span class="name"><%= link_to @random_users[3].name, user_path(@random_users[3].id)%></span> 
            and <span class="name"><%= link_to @random_users[4].name, user_path(@random_users[4].id)%></span></p>
        </div>
    </div>
</div>


<% if user_signed_in? %>
<div class="button black">
    <%= link_to "Log out", destroy_user_session_path, :method => :delete  %>
</div>
<% end %>

app/views/matches/index.html.erb
<% @matches.each do |match| %>
    <h1><%= match.created_at %></h1>
<% end %>

app/views/static_pages/conversations.html.erb
<div class="section-heading top-margin">
    <h1>Conversations menu</h1>
    <p>In case you run out of things to talk about, here are some suggestions.</p>
</div>

<div class="conversations-list">
    <div class="conversation-item">
        <div class="content">
            <h4>Starter</h4>
            <h3 class="date">How has technology changed your life in the last 5 years?</h3>
        </div>
    </div>
    <div class="conversation-item">
        <div class="content">
            <h4>Main</h4>
            <h3 class="date">What new skill would you like to learn?</h3>
        </div>
    </div>
       <div class="conversation-item">
        <div class="content">
            <h4>Dessert</h4>
            <h3 class="date">Would you rather fight 100 duck sized horses or 1 horse sized duck?l</h3>
        </div>
    </div>
</div>

<div class="button pink">
  <%= link_to "Go home", lunches_url %>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <%= user.name %>
<% end %>

app/views/users/new.html.erb
<h1>Welcome</h1>

<%= form_for @user, url: { action: "create" } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.label :department %>
  <%= f.collection_select :department_id, @departments, :id, :name %>
  <br />
  <%= f.label "LinkedIn URL (optional)" %>
  <%= f.text_field :url %>
  <br />
  <%= submit_tag 'Create' %>
<% end %>

app/views/users/show.html.erb
 <% if  @user %>
<div class="profile-box top">
    <img src="<%= image_path('face.png') %>" class="face"/>
    <span class="name">
        <%= @user.name %>
    </span>
    <% if @user.department != nil %>
    <span class="department">
        <%= @user.department.name %>
    </span>
    <% end %>
</div>

<div class="profile-box">
    <span>
        <%= mail_to @user.email %>
    </span>
</div>

<div class="profile-box">
    <span>
        555 555 55 55
    </span>
</div>

<div class="button">
   <%= link_to "go to linkedin", "https://www.linkedin.com/", :target => "_blank" %>
</div>

<div class="button pink">
   <%= link_to "Go home", root_url %>
</div>
<% end %>